return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.2.2",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 16,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 3,
  nextobjectid = 321,
  properties = {},
  tilesets = {
    {
      name = "SpriteSheet",
      firstgid = 1,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 5,
      image = "../SpriteSheet.png",
      imagewidth = 160,
      imageheight = 160,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 25,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 1,
      name = "World",
      x = 0,
      y = 0,
      width = 16,
      height = 16,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "lua",
      chunks = {
        {
          x = -32, y = -80, width = 16, height = 16,
          data = {
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
          }
        },
        {
          x = -16, y = -80, width = 16, height = 16,
          data = {
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
          }
        },
        {
          x = 0, y = -80, width = 16, height = 16,
          data = {
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
          }
        },
        {
          x = -32, y = -64, width = 16, height = 16,
          data = {
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
          }
        },
        {
          x = -16, y = -64, width = 16, height = 16,
          data = {
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
          }
        },
        {
          x = 0, y = -64, width = 16, height = 16,
          data = {
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
          }
        },
        {
          x = -32, y = -48, width = 16, height = 16,
          data = {
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
          }
        },
        {
          x = -16, y = -48, width = 16, height = 16,
          data = {
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
          }
        },
        {
          x = 0, y = -48, width = 16, height = 16,
          data = {
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
          }
        },
        {
          x = -32, y = -32, width = 16, height = 16,
          data = {
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
          }
        },
        {
          x = -16, y = -32, width = 16, height = 16,
          data = {
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
          }
        },
        {
          x = 0, y = -32, width = 16, height = 16,
          data = {
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
          }
        },
        {
          x = -32, y = -16, width = 16, height = 16,
          data = {
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
          }
        },
        {
          x = -16, y = -16, width = 16, height = 16,
          data = {
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
          }
        },
        {
          x = 0, y = -16, width = 16, height = 16,
          data = {
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 2,
      name = "Obstacles",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = -160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = -992,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = -928,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = -960,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = -896,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = -864,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = -832,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = -800,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = -736,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = -768,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = -704,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = -672,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = -640,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = -608,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = -576,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = -544,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = -512,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = -480,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = -448,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = -416,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = -384,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = -352,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = -320,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = -288,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = -256,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = -224,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = -192,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = -160,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = -128,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = -96,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = -32,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "",
          shape = "rectangle",
          x = -64,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -2528,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -2496,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -2464,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -2400,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -2368,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -2432,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -2304,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -2336,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -2272,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -2208,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -2176,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -2240,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -2112,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -2080,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -2144,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -2016,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -2048,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1984,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1952,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1856,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1920,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1888,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1792,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1824,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1760,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1696,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1664,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1728,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1600,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1568,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1632,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1536,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1472,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1408,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1504,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1440,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1376,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 124,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1344,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1280,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 126,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1216,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 127,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1312,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1248,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 129,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1184,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1152,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 131,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1088,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1024,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 133,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1120,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 134,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -1056,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 135,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -960,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 136,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -992,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 137,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -928,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 138,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -896,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 139,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -832,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 140,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -800,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 141,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -864,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 142,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -736,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 143,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -768,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 144,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -704,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 145,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -672,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 146,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -608,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 147,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -544,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 148,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -640,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -576,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 150,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -512,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 151,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -480,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 152,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -416,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 153,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -448,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 156,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 158,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 159,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 161,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 162,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 163,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 164,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 165,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 166,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 167,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 168,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 169,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 170,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 171,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 172,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 174,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 175,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 176,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 177,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 178,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 179,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 180,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 181,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 182,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 183,
          name = "",
          type = "",
          shape = "rectangle",
          x = -32,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 188,
          name = "",
          type = "",
          shape = "rectangle",
          x = -128,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 189,
          name = "",
          type = "",
          shape = "rectangle",
          x = -96,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 190,
          name = "",
          type = "",
          shape = "rectangle",
          x = -64,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 191,
          name = "",
          type = "",
          shape = "rectangle",
          x = -160,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 192,
          name = "",
          type = "",
          shape = "rectangle",
          x = -192,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 193,
          name = "",
          type = "",
          shape = "rectangle",
          x = -256,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 194,
          name = "",
          type = "",
          shape = "rectangle",
          x = -224,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 195,
          name = "",
          type = "",
          shape = "rectangle",
          x = -288,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 196,
          name = "",
          type = "",
          shape = "rectangle",
          x = -320,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 197,
          name = "",
          type = "",
          shape = "rectangle",
          x = -352,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 198,
          name = "",
          type = "",
          shape = "rectangle",
          x = -416,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 199,
          name = "",
          type = "",
          shape = "rectangle",
          x = -384,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 200,
          name = "",
          type = "",
          shape = "rectangle",
          x = -448,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 201,
          name = "",
          type = "",
          shape = "rectangle",
          x = -512,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 202,
          name = "",
          type = "",
          shape = "rectangle",
          x = -480,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 203,
          name = "",
          type = "",
          shape = "rectangle",
          x = -544,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 204,
          name = "",
          type = "",
          shape = "rectangle",
          x = -608,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 205,
          name = "",
          type = "",
          shape = "rectangle",
          x = -576,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 206,
          name = "",
          type = "",
          shape = "rectangle",
          x = -640,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 207,
          name = "",
          type = "",
          shape = "rectangle",
          x = -672,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 208,
          name = "",
          type = "",
          shape = "rectangle",
          x = -736,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 209,
          name = "",
          type = "",
          shape = "rectangle",
          x = -704,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 210,
          name = "",
          type = "",
          shape = "rectangle",
          x = -768,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 211,
          name = "",
          type = "",
          shape = "rectangle",
          x = -800,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 212,
          name = "",
          type = "",
          shape = "rectangle",
          x = -832,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 213,
          name = "",
          type = "",
          shape = "rectangle",
          x = -896,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 214,
          name = "",
          type = "",
          shape = "rectangle",
          x = -864,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 215,
          name = "",
          type = "",
          shape = "rectangle",
          x = -928,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 216,
          name = "",
          type = "",
          shape = "rectangle",
          x = -960,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 217,
          name = "",
          type = "",
          shape = "rectangle",
          x = -992,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 218,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 219,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 220,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 221,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 222,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 223,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 224,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 225,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 226,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 227,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 228,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 229,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 230,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -416,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 231,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 232,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -448,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 233,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -512,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 234,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -480,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 235,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -544,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 236,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -608,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 237,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -576,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 238,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -640,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 239,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -704,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 240,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -736,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 241,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -672,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 244,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -768,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 245,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -800,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 246,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -864,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 247,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -832,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 248,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1632,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 249,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1600,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 250,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1568,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 251,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1536,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 252,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1504,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 253,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1440,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 254,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1408,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 255,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1344,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 256,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1280,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 257,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1216,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 258,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1152,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 259,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1056,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 260,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -960,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 261,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -928,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 262,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -896,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 263,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -992,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 264,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1024,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 265,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1088,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 266,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1120,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 267,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1184,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 268,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1248,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 269,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1312,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 270,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1376,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 271,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1472,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 272,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1664,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 273,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1696,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 274,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1760,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 275,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1728,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 279,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1792,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 280,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1824,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 281,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1856,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 282,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1888,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 283,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1920,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 284,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1952,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 285,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -1984,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 286,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -2016,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 287,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -2048,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 288,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -2080,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 289,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -2112,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 290,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -2144,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 291,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -2176,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 292,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -2208,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 293,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -2240,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 294,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -2304,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 295,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -2336,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 297,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -2272,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 298,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -2368,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 299,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -2400,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 300,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -2464,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 301,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -2432,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 302,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1024,
          y = -2496,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 303,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = -352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 304,
          name = "",
          type = "",
          shape = "rectangle",
          x = -192,
          y = -384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 305,
          name = "",
          type = "",
          shape = "rectangle",
          x = -448,
          y = -192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 306,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = -576,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 307,
          name = "",
          type = "",
          shape = "rectangle",
          x = -320,
          y = -608,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 308,
          name = "",
          type = "",
          shape = "rectangle",
          x = -224,
          y = -384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 309,
          name = "",
          type = "",
          shape = "rectangle",
          x = -224,
          y = -352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 310,
          name = "",
          type = "",
          shape = "rectangle",
          x = -192,
          y = -352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 311,
          name = "",
          type = "",
          shape = "rectangle",
          x = -224,
          y = -320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 312,
          name = "",
          type = "",
          shape = "rectangle",
          x = -192,
          y = -320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 313,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = -160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 314,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = -192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 315,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = -224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 316,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = -192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 317,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = -160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 318,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = -224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 319,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = -224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 320,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = -192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
