return {
  ROW_COOLDOWN = 1.15,
  ROW_BAR_WIDTH = 0.5,
  ROW_BAR_HEIGHT = 0.06,
  ROW_ANGLE_DELTA = 0.05 * math.pi,
  WATER_FRICTION = 1.3,
  BOAT_ROW_FORCE = 800,
  ORIENTATION_CHANGE_TIME = 5,
  WINDOWED_RESOLUTION = {x = 1280, y = 720},
  CAMERA_DAMPENING = 15
}
